# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'mime/types'

img = File.join(Rails.root, "/app/assets/images/seed_icon/school.png") 
Icon.create(name_icon: '学校、仕事', image_icon: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/お出かけ.png") 
Icon.create(name_icon: 'お出かけ',image_icon: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/趣味.png") 
Icon.create(name_icon: '趣味', image_icon: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/習い事.png") 
Icon.create(name_icon: '習い事', image_icon: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/病院.png") 
Icon.create(name_icon: '病院', image_icon: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/買い物.png") 
Icon.create(name_icon: '買い物', image_icon: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/0.png") 
Genre.create(color_g: '0', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/1.png") 
Genre.create(color_g: '1', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/2.png") 
Genre.create(color_g: '2', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/3.png") 
Genre.create(color_g: '3', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/4.png") 
Genre.create(color_g: '4', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/5.png") 
Genre.create(color_g: '5', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/6.png") 
Genre.create(color_g: '6', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/7.png") 
Genre.create(color_g: '7', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/8.png") 
Genre.create(color_g: '8', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/9.png") 
Genre.create(color_g: '9', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/10.png") 
Genre.create(color_g: '10', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/11.png") 
Genre.create(color_g: '11', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/12.png") 
Genre.create(color_g: '12', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/13.png") 
Genre.create(color_g: '13', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/14.png") 
Genre.create(color_g: '14', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/15.png") 
Genre.create(color_g: '15', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/16.png") 
Genre.create(color_g: '16', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/17.png") 
Genre.create(color_g: '17', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/18.png") 
Genre.create(color_g: '18', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/19.png") 
Genre.create(color_g: '19', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/20.png") 
Genre.create(color_g: '20', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/21.png") 
Genre.create(color_g: '21', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/22.png") 
Genre.create(color_g: '22', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/23.png") 
Genre.create(color_g: '23', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/24.png") 
Genre.create(color_g: '24', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/25.png") 
Genre.create(color_g: '25', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/26.png") 
Genre.create(color_g: '26', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/27.png") 
Genre.create(color_g: '27', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/28.png") 
Genre.create(color_g: '28', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/29.png") 
Genre.create(color_g: '29', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/30.png") 
Genre.create(color_g: '30', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/31.png") 
Genre.create(color_g: '31', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/32.png") 
Genre.create(color_g: '32', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/33.png") 
Genre.create(color_g: '33', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/34.png") 
Genre.create(color_g: '34', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/35.png") 
Genre.create(color_g: '35', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/36.png") 
Genre.create(color_g: '36', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/37.png") 
Genre.create(color_g: '37', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/38.png") 
Genre.create(color_g: '38', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/39.png") 
Genre.create(color_g: '39', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/40.png") 
Genre.create(color_g: '40', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/41.png") 
Genre.create(color_g: '41', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/42.png") 
Genre.create(color_g: '42', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/43.png") 
Genre.create(color_g: '43', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/44.png") 
Genre.create(color_g: '44', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/45.png") 
Genre.create(color_g: '45', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/46.png") 
Genre.create(color_g: '46', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/47.png") 
Genre.create(color_g: '47', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/48.png") 
Genre.create(color_g: '48', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/49.png") 
Genre.create(color_g: '49', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
img = File.join(Rails.root, "/app/assets/images/seed_icon/50.png") 
Genre.create(color_g: '50', image_g: File.basename(img), image_binary: File.open(img,"rb").read, image_type: MIME::Types.type_for(img)[0].to_s)
